# Generated by Django 3.1.1 on 2020-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.AddField(
            model_name='winner',
            name='winner_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
