# Generated by Django 3.1.1 on 2020-09-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='repassword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
