# Generated by Django 3.1.1 on 2020-09-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0004_auto_20200926_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='repassword',
        ),
    ]
