# Generated by Django 3.1.1 on 2020-10-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0005_auto_20200927_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='email',
        ),
        migrations.AddField(
            model_name='adherent',
            name='score',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
