# Generated by Django 3.1.1 on 2020-10-04 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkers', '0006_auto_20201001_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
