# Generated by Django 3.1.1 on 2020-11-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0010_auto_20201106_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_session',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_session',
            name='game_id',
            field=models.CharField(max_length=255),
        ),
    ]
