# Generated by Django 3.1.1 on 2020-11-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0012_auto_20201106_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_session',
            name='game_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
