# Generated by Django 3.1.1 on 2020-11-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0014_auto_20201106_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Session',
        ),
    ]
