# Generated by Django 3.1.1 on 2020-11-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0016_game_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_session',
            old_name='player1_usrname',
            new_name='player1_username',
        ),
    ]
