# Generated by Django 3.1.1 on 2020-11-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0017_auto_20201106_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_session',
            name='game_object',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
