# Generated by Django 3.1.1 on 2020-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0018_game_session_game_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_session',
            name='game_object',
            field=models.TextField(),
        ),
    ]
