# Generated by Django 3.1.1 on 2020-11-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0019_auto_20201106_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_session',
            name='is_open_to_join',
            field=models.BooleanField(default=True),
        ),
    ]
