# Generated by Django 3.1.1 on 2020-11-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0022_auto_20201108_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
