# Generated by Django 3.1.1 on 2020-09-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('is_playing', models.BooleanField()),
                ('link_old_game', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pieces', models.IntegerField()),
                ('positions', models.CharField(max_length=10)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_move_valid', models.BooleanField(max_length=20)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.game')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('is_crowned', models.BooleanField()),
                ('GameBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.gameboard')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.player'),
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('routeoldgame', models.CharField(max_length=30)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.player')),
            ],
        ),
    ]
